[package]
name = "rust-calculator"
version = "0.1.0"
authors = ["Stefan Holzm√ºller <stefanholzmueller@github>"]
edition = "2018"

[dependencies]
combine = "3.8.1"
num-bigint = "0.2.2"
num-rational = "0.2.1"
